import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import NavBar from "./Component/NavBar";
import Footer from "./Component/Footer";

export const metadata: Metadata = {
  title: "현종선박임대.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const language = (cookieStore.get("language")?.value || "ko") as "ko" | "en";

  return (
    <html lang="en">
      <body>
        {/* Navigation */}
        <NavBar defaultLanguage={language} />
        {children}
        <Footer />
      </body>
    </html >
  );
}
