import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LanguageSelector from "./Component/LanguageSelector";
import { cookies } from "next/headers";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "테스트 사이트입니다.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const language = (cookieStore.get("language")?.value || "ko") as "ko" | "en";
  return (
    <html lang="en">
      <body
      >
        {/* Navigation */}
        <nav className="bg-white shadow-md py-4 px-10 text-center flex items-center justify-between ">
          <Image src="/logo.png" alt="logo" width={150} height={200} className="object-cover" />
          <ul className="flex justify-center space-x-6">
            <li><Link href="/about" className="text-blue-600 hover:underline">회사소개</Link></li>
            <li><Link href="/services" className="text-blue-600 hover:underline">사업분야</Link></li>
            <li><Link href="/support" className="text-blue-600 hover:underline">고객지원</Link></li>
            <li><Link href="/sitemap" className="text-blue-600 hover:underline">사이트 맵</Link></li>
          </ul>
          <LanguageSelector defaultLanguage={language} />
        </nav>
        {children}
      </body>
    </html>
  );
}
