import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import LanguageSelector from "./Component/LanguageSelector";
import { cookies } from "next/headers";
import HomepageLink from "./Component/HomepageLink";



export const metadata: Metadata = {
  title: "테스트 사이트입니다.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const language = (cookieStore.get("language")?.value || "ko") as "ko" | "en";
  return (
    <html lang="en">
      <body
      >
        {/* Navigation */}
        <nav className="bg-white shadow-md py-4 px-10 text-center flex items-center justify-between">
          <HomepageLink />
          <div className="flex items-center gap-8">
            <ul className="flex justify-center space-x-6">
              <li><Link href="/about" className="text-gray-800 hover:underline">회사소개</Link></li>
              <li><Link href="/services" className="text-gray-800 hover:underline">사업분야</Link></li>
              <li><Link href="/support" className="text-gray-800 hover:underline">고객지원</Link></li>
              <li><Link href="/sitemap" className="text-gray-800 hover:underline">사이트 맵</Link></li>
            </ul>
            <LanguageSelector defaultLanguage={language} />
          </div>
        </nav>
        {children}
      </body>
    </html >
  );
}
